name: initialize-runner
description: Initialize runner
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install dev requirements
      shell: bash
      run: python3 -m pip install -r requirements.txt -r requirements.dev.txt --upgrade
