name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  precheck:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/initialize-runner
      - name: black linter
        shell: bash
        run: python3 -m black . --check
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.1
        with:
          args: --baseline,./ci-files/qodana.sarif.json
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
