name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  precheck:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/initialize-runner
      - name: black linter
        shell: bash
        run: python3 -m black . --check
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/initialize-runner
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.1
